apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config
data:
  sample.cfg: |
    user: max
  type: "application"

---
apiVersion: v1
kind: Pod
metadata: 
  name: sample
spec:
  containers:
    - name: sample
      image: nginx:1.17.2-alpine
      env:
        - name: type
          valueFrom:
            configMapKeyRef:
              name: sample-config
              key: type
      volumeMounts:
        - name: config-storage
          mountPath: /home/nginx
  volumes:
    - name: config-storage
      configMap:
        name: sample-config
        items:
          - key: sample.cfg
            path: sample.cfg
